baseURL = "https://bananaeducation.netlify.app/"

languageCode = "fr-fr"
DefaultContentLanguage = "fr"
title = "Banana Comptabilité Education"
theme = "ace-documentation"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
enableGitInfo = true

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableReadmoreNav = false # set true to hide prev/next navigation, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<button class='btn btn-primary mt-n1'>Download</button>"
url = "https://www.banana.ch/fr/download"
weight = 3

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]